### ISSUE TITLE
borgClinet connection error

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/borg#33]
I have tried to run the react-cra example app and it is not able to connect to server.

## steps:
1. rushx start --> in the server folder
2. rushx start --> in the react-cra folder
3. press the connect button in the example app screen

## Error log:

`index.js:49040 Error: stream ended before 1 bytes became available
    at index.js:36:1
    at async decoder (decode.js:113:1)
    at async first (index.js:11:1)
    at async Object.push.../../common/temp/node_modules/.pnpm/multistream-select@2.0.1/node_modules/multistream-select/src/multistream.js.exports.read (multistream.js:31:1)
    at async push.../../common/temp/node_modules/.pnpm/multistream-select@2.0.1/node_modules/multistream-select/src/select.js.module.exports (select.js:21:1)
    at async Connection.newStream [as _newStream] (upgrader.js:263:1)
    at async Connection.newStream (connection.js:175:1)
    at async ping (index.js:37:1)
    at async Object.connect (index.js:49036:1)
    at async connect (FileTransfer.tsx:50:1)`

**Comment by farhoud** [comment]
Hi @ghorbani-m 
you have to update your node to 16 because ipfs decide to remove some ploy-fill from its packages.
[more info ](https://github.com/ipfs/js-ipfs/pull/4015)
